const SENTENCES = [
  "You are loved more than you know.",
  "Today is a gift — and so are you.",
  "The world is brighter with you in it.",
  "You are doing better than you think.",
  "Something wonderful is always unfolding around you.",
  "You matter deeply to the people in your life.",
  "Every breath is a fresh new beginning.",
  "You are exactly where you need to be.",
  "Life is full of moments worth celebrating — including right now.",
  "Your presence makes a difference.",
  "You carry so much light within you.",
  "There is beauty in this very moment, just as it is.",
  "You have made it through every hard day so far — that is remarkable.",
  "Someone out there is grateful you exist.",
  "Your kindness ripples further than you can see.",
  "You deserve all the good things heading your way.",
  "The best is still ahead of you.",
  "You are stronger than any storm you face.",
  "Small joys are everywhere — keep your eyes open.",
  "You are never as alone as you might feel.",
  "Today, give yourself the grace you freely give others.",
  "You are a whole universe of possibility.",
  "Everything you need is already within you.",
  "Your story is still being written, and it is a good one.",
  "Joy is your birthright — claim it today.",
  "You have so much to offer the world.",
  "The people who love you are thinking of you right now.",
  "Your heart is bigger than you give it credit for.",
  "There is something beautiful waiting for you today.",
  "You are enough, exactly as you are.",
  "Gratitude turns what you have into more than enough.",
  "You are a rare and wonderful person.",
  "Today holds something good just for you.",
  "You have overcome hard things before — you will again.",
  "Your smile has the power to change someone's whole day.",
  "You belong here, fully and completely.",
  "Life is rooting for you.",
  "Your potential has no ceiling.",
  "Right now, in this moment, you are enough.",
  "Warmth and connection are always closer than they seem.",
  "You are allowed to feel proud of how far you have come.",
  "Every day you are becoming more of who you are meant to be.",
  "You are seen, valued, and appreciated.",
  "The universe conspires in your favor more often than you notice.",
  "You light up every room you walk into.",
  "There is deep magic in the ordinary moments of your life.",
  "You have a gift the world genuinely needs.",
  "Happiness lives in the small things — look closely.",
  "You are worthy of every good thing that comes your way.",
  "Your courage shows up every single day, even when you cannot see it.",
  "Something you did recently made someone else's day better.",
  "You are held by more love than you realize.",
  "Peace is available to you in this very breath.",
  "Your dreams are valid and worth pursuing.",
  "You make the world a kinder place just by being in it.",
  "Today is full of chances to feel alive and grateful.",
  "You are loved, fully and without condition.",
  "Your best days are not behind you — they are being built right now.",
  "There is always more beauty ahead.",
  "You are worthy of rest, joy, and belonging.",
  "Even tiny steps forward are still moving you forward.",
  "You have something no one else has — your unique heart.",
  "Abundance surrounds you if you look with open eyes.",
  "You are never forgotten by the people who matter.",
  "Today is another chance to feel wonder.",
  "You are doing something right — even when it feels invisible.",
  "Good things are growing in your life, even underground.",
  "You are a walking miracle.",
  "The love in your life is real and it is growing.",
  "You are exactly enough for this moment.",
  "There is warmth waiting for you in unexpected places today.",
  "Your presence is a blessing to those who know you.",
  "You have the power to create joy for yourself and others.",
  "Everything is working out for you in ways you cannot yet see.",
  "You are surrounded by more goodness than you notice.",
  "The fact that you keep going is something to admire.",
  "There is someone in your life who is so glad you exist.",
  "You are deeply rooted and beautifully growing.",
  "Something magnificent is quietly taking shape in your life.",
  "You are a source of light for people around you.",
  "You have earned every good thing in your life.",
  "Today, may you feel the warmth of being truly alive.",
  "You are braver than you believe.",
  "Your heart knows the way — trust it.",
  "Great things are coming to you.",
  "You are a gift to everyone who gets to know you.",
  "There is so much richness in your life worth savoring.",
  "You are connected to something much larger than yourself.",
  "The kindness you give always finds its way back to you.",
  "You are capable of extraordinary things.",
  "Every challenge you have faced has made you wiser.",
  "You are deeply, truly worthy of happiness.",
  "Today is a good day to feel grateful — and you deserve to.",
  "Your life is a beautiful, ongoing adventure.",
  "You are not alone — not now, not ever.",
  "There is so much good still to come.",
  "You matter — more than words can hold.",
  "The world needs exactly the person that you are.",
  "You are loved. You are enough. You are here — and that is everything."
];
